add some java8 modules which have been removed.
fix for error
repo
https://github.com/FasterXML/jackson-modules-java8

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling